### ISSUE TITLE
incorporate a headers param to MockRequest.get()

### ISSUE THREAD

**Issue by adrian-datacamp** [adrian-soto/mock-request#5]
needed to pass API keys and other important API parameters

**Comment by adrian-soto** [comment]
On a second thought, I decided to [undo this](https://github.com/adrian-soto/mock-request/commit/5a977c8430235fcc6c650a0a7eb66b9b63d12459#diff-ec5765bfb39d653f10fe6c84821cafe5L86) because it would add extra entries in the params dict that would make the mock request not match what's in the lookup table. Not necessary for right now, later on I can decide to add a workaround to this.
